### ISSUE TITLE
Generate entity add simple quote into table name tag

### ISSUE THREAD

**Issue by achablowski** [jaxio/celerio-angular-quickstart#22]
Hello,

I have some trouble with the entity generation.
I have a table named "Delay", but when the template generate the corresponding entity, a simple quote is added to the name, and then i get oracle problems in request "Table or view no exist".

**@Table(name = " \` DELAY \` "...** 
instead of 
**@Table(name = "DELAY"...**

Regards,

Thanks.

**Comment by nromanetti** [comment]
Hi, Celerio considers the DELAY as a reserved keyword (used in some version of PLSQL) and escape it... but apparently it does not escape it properly since JPA 2.
Have a look at http://stackoverflow.com/questions/2153881/using-reserved-jpql-keywords-with-jpa

Since you are using Oracle, could you please do me a favor and try to escape it as specified by JPA 2, that is:

@Table(name="\"DELAY\""...

If it works out I can patch Celerio.
Thanks.

**Comment by achablowski** [comment]
Hi,

Thanks, it's okay i renamed the table.

Regards,
